TRIES: 3 # number of times to retry each failed example

MAX_INLINE_TEST_CHARS: 10000 # 4 chars ~= 1 token

MAX_CHARS_LIMIT: 25000


AMT_WORKERS: 2 # set to -1 to use all workers available

# Eval
EVAL_OUTPUT_FILE_NAME: out/benchmark/t3_benchmark_results.json

AMOUNT_OF_EVAL_SAMPLES: 1000 # set to -1 to use all eval samples

EVAL_FAILED_FILE: out/logs/eval_failed.txt

CODEREADER_CONFIG_FILE: pipeline/codereader.yml
