TRIES: 3 # number of times to retry each failed example

MAX_INLINE_TEST_CHARS: 10000 # 4 chars ~= 1 token

MAX_CHARS_LIMIT: 25000

AMT_WORKERS: 1 # set to -1 to use all workers available, check if your api allows multi threading else set to 1

LOCAL: false # make use of local model instead of api

# Eval
EVAL_OUTPUT_FILE_NAME: out/benchmark/t3_benchmark_results.json

AMOUNT_OF_EVAL_SAMPLES: 10 # set to -1 to use all eval samples

EVAL_FAILED_FILE: out/logs/eval_failed.txt

CODEREADER_CONFIG_FILE: pipeline/codereader.yml
